### PR TITLE
Fixes #5

### LINKED ISSUE #5: Remove `server` from git
It is not advisable to keep binary files in git index.

Remove `server` binary file and add it to `.gitignore`

### PR DESCRIPTION
**Pull request by skprabhanjan**
@Hrily , Please check this PR that fixes #5  .
Thanks :)

### CODE REVIEW

**Review by Hrily — CHANGES_REQUESTED** [review]
You also need to remove `server` from git index.
Use `git rm server`, then commit and then push

**Comment by skprabhanjan** [comment]
I have done that already and doing that again throws **fatal: pathspec 'server' did not match any files**

**Comment by Hrily** [comment]
Try doing normal `rm` and commit

**Comment by skprabhanjan** [comment]
I dont have that file itself, I have deleted it only and committed.

**Comment by Hrily** [comment]
Try `git rm --cached server` and commit

**Comment by skprabhanjan** [comment]
I tried that also, i dont have the file locally itself.

**Comment by Hrily** [comment]
Let us check if merging removes the file.

**Comment by Hrily** [comment]
It did. Sorry for the trouble.

**Pull request merged**
